spring:
  jpa.hibernate:
    ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/jandy?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: true
    validation-query: SELECT 1
    test-on-borrow: true
