spring:
  application.name: jandy
  oauth2:
    client:
      clientId: 5b6118bdbd4066c1ea7a
      clientSecret: 33e25aa49db0a3113ab222473b8e5483e5ec637d
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
      scope:
        - user
        - public_repo
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false
  freemarker:
    requestContextAttribute: rc
security:
  basic.path: /login
server.port: 3000

logging.level.io.jandy: TRACE